title: ZhengYang Yang's Homepage
page-top-title: ZhengYang Yang
top-section-bg-text: Computational Mathematics
home-subtitle: ZhengYang Yang&ensp;|&ensp;杨正阳
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
